# Generated by Django 4.2.27 on 2025-12-31 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.URLField(unique=True)),
                ("definition", models.JSONField(default=dict)),
                ("object_type", models.CharField(default="Activity", max_length=50)),
                ("moodle_activity_id", models.IntegerField(blank=True, null=True)),
                ("moodle_course_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.CharField(max_length=500, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("Agent", "Agent"), ("Group", "Group")], max_length=20
                    ),
                ),
                ("object_type", models.CharField(default="Agent", max_length=50)),
                ("mbox", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mbox_sha1sum",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("openid", models.URLField(blank=True, null=True)),
                ("account_homepage", models.URLField(blank=True, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("moodle_user_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoodleIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moodle_url", models.URLField()),
                ("moodle_token", models.CharField(max_length=255)),
                ("moodle_site_name", models.CharField(max_length=255)),
                ("web_service_user", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb_id", models.URLField()),
                ("display", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("object", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, default=dict, null=True)),
                ("context", models.JSONField(blank=True, default=dict, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("stored", models.DateTimeField(auto_now_add=True)),
                ("authority", models.JSONField(blank=True, default=dict, null=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("moodle_data", models.JSONField(blank=True, default=dict, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="lrs.activity",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="lrs.actor",
                    ),
                ),
                (
                    "verb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="lrs.verb",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
