# Generated by Django 4.2.27 on 2025-12-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lrs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodleintegration",
            name="web_service_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
