# Generated by Django 4.2.27 on 2025-12-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lrs", "0002_alter_moodleintegration_web_service_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodleintegration",
            name="auto_sync",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                ],
                default="disabled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="moodleintegration",
            name="lrs_endpoint",
            field=models.URLField(
                blank=True, help_text="LRS endpoint for this Moodle instance", null=True
            ),
        ),
    ]
